services:
  - type: web
    name: fitness-app-backend
    env: node
    plan: free
    root: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://fitnessuser:fitnesspass123@cluster0.mongodb.net/fitnessdb?retryWrites=true&w=majority
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://fitness-app-client.onrender.com
    routes:
      - path: /api
        destination: http://localhost:5000/api

  - type: static
    name: fitness-app-client
    root: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://fitness-app-backend.onrender.com
